spring.application.name=product-service
server.port=8083

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/motori_products}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}

#swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.info.env.enabled=true

# Info du service
info.app.name=product-service
info.app.version=1.0.0
info.app.description=Microservice de gestion de pièces et équipements moto

# Logs
logging.level.com.motori.product_service=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

#minio
minio.url=http://localhost:9000
minio.access-key=motori
minio.secret-key=motori123
minio.bucket=motori-products

# Keycloak JWT validation
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8082/realms/motori



