spring.application.name=product-service
server.port=8083

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/motori_products}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:toor}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=product-service
info.app.version=1.0.0
info.app.description=Microservice de gestion de pièces et équipements moto

# Logs
logging.level.com.motori.product_service=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# MinIO
minio.url=${MINIO_URL:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:motori}
minio.secret-key=${MINIO_SECRET_KEY:motori123}
minio.bucket=${MINIO_BUCKET:motori-products}

# Keycloak JWT — issuer-uri must match the hostname Keycloak uses to sign tokens
# In Docker: motori-keycloak:8080 (internal), locally: localhost:8082
spring.security.oauth2.resourceserver.jwt.issuer-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8082/realms/motori_realm}

# Redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.show-actuator=true
server.forward-headers-strategy=framework
springdoc.swagger-ui.config-url=/api/products/api-docs/swagger-config
springdoc.swagger-ui.url=/api/products/api-docs
springdoc.swagger-ui.oauth2-redirect-url=/api/products/swagger-ui/oauth2-redirect.html
springdoc.swagger-ui.csrf.enabled=false
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.paths-to-match=/api/**    